server:
  port: ${SERVER_PORT:8099}
spring:
  application:
    name: publisher-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:bookrush}
    username: ${DB_USERNAME:bookrush}
    password: ${DB_PASSWORD:bookrush}
  flyway:
    schemas: publisher
management:
  endpoints.web.exposure.include: health,info,metrics
