import { useQuery } from '@tanstack/react-query';
import { Heart, RotateCcw, Save, SlidersHorizontal, ThumbsDown } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useAuth } from '../../auth/useAuth';
import { defaultWeights } from '../../mocks/data';
import { services } from '../../lib/services';
import { FeedWeights, TrainingSession } from '../../types/domain';

const labels:Record<keyof FeedWeights,string>={hook:'Hook',novelty:'Novelty',affinity:'Affinity',readability:'Readability',diversity:'Diversity',exploration:'Exploration'};

export function FeedLabPage(){
 const auth=useAuth(); const feed=useQuery({queryKey:['feed'],queryFn:()=>services.getFeed()});
 const [session,setSession]=useState<TrainingSession>(); const [weights,setWeights]=useState<FeedWeights>(defaultWeights); const initialWeights=useRef(weights).current; const [index,setIndex]=useState(0);
 useEffect(()=>{void services.createSession(auth.userId,initialWeights).then(setSession)},[auth.userId,initialWeights]);
 const item=feed.data?.[index%Math.max(feed.data?.length??1,1)];
 useEffect(()=>{if(!session||!item)return; const started=Date.now(); void services.emitEvent({sessionId:session.id,excerptId:item.excerptId,type:'IMPRESSION',occurredAt:new Date().toISOString(),parameterVersion:session.parameterVersion}); const onVisibility=()=>{if(document.visibilityState==='hidden'){void services.emitEvent({sessionId:session.id,excerptId:item.excerptId,type:'DWELL',value:Date.now()-started,occurredAt:new Date().toISOString(),parameterVersion:session.parameterVersion});}}; document.addEventListener('visibilitychange',onVisibility); return()=>{document.removeEventListener('visibilitychange',onVisibility); if(document.visibilityState==='visible')void services.emitEvent({sessionId:session.id,excerptId:item.excerptId,type:'DWELL',value:Date.now()-started,occurredAt:new Date().toISOString(),parameterVersion:session.parameterVersion});};},[session,item]);
 const emit=async(type:'LIKE'|'DISLIKE'|'SAVE'|'OPEN_BOOK'|'SKIP', value?:number)=>{if(!session||!item)return;await services.emitEvent({sessionId:session.id,userId:auth.userId,excerptId:item.excerptId,type,value,occurredAt:new Date().toISOString(),parameterVersion:session.parameterVersion});if(type==='SKIP'||type==='LIKE'||type==='DISLIKE')setIndex(i=>i+1)};
 const update=async(k:keyof FeedWeights,v:number)=>{const nw={...weights,[k]:v};setWeights(nw);if(session){const s=await services.updateWeights(session.id,nw);setSession({...s})}};
 if(feed.isLoading)return <p>Loading feed…</p>;
 if(feed.isError)return <section className="panel"><h1>Feed Lab indisponível</h1><p>{feed.error instanceof Error ? feed.error.message : 'O serviço de feed não respondeu.'}</p><p>O catálogo, analytics e ingestão continuam independentes; configure a rota `/feed` quando o serviço de feed estiver implantado.</p></section>;
 if(!item)return <section className="panel"><h1>Nenhum excerpt disponível</h1><p>Execute analytics e gere candidatos antes de iniciar uma sessão de treino.</p></section>;
 return <section><header className="pagehead"><div><span className="eyebrow">RECOMMENDATION LAB</span><h1>Feed Lab</h1><p>Use usuários administrativos como população inicial para gerar eventos de interação e calibrar o ranking.</p></div><div className="sessionbadge">Session {session?.id?.slice(-6)??'...'}</div></header>
 <div className="labgrid"><div className="phone"><div className="phonebar"><span>TRAINING</span><strong>{index+1}</strong></div><div className="excerpt"><div className="score">score {Number(item.rankScore ?? 0).toFixed(2)}</div><blockquote>“{item.text}”</blockquote><div><strong>{item.bookTitle}</strong><span>{item.author}</span></div></div><div className="actions"><button onClick={()=>emit('DISLIKE')}><ThumbsDown/></button><button onClick={()=>emit('LIKE')}><Heart/></button><button onClick={()=>emit('SAVE')}><Save/></button></div><button className="next" onClick={()=>emit('SKIP')}>Skip / next excerpt</button></div>
 <aside className="tuner"><div className="tunerhead"><div><SlidersHorizontal size={18}/><h2>Ranking parameters</h2></div><button onClick={()=>setWeights(defaultWeights)}><RotateCcw size={15}/></button></div><p>Cada alteração gera uma nova versão de parâmetros associada aos próximos eventos.</p>{(Object.keys(weights) as (keyof FeedWeights)[]).map(k=><label key={k}><div><span>{labels[k]}</span><strong>{weights[k].toFixed(2)}</strong></div><input aria-label={labels[k]} type="range" min="0" max="1" step="0.01" value={weights[k]} onChange={e=>update(k,+e.target.value)}/></label>)}<div className="version"><span>Parameter version</span><code>{session?.parameterVersion??'creating...'}</code></div><div className="featurebox"><span>Score decomposition</span>{Object.entries(item.features).map(([k,v])=><div key={k}><span>{k}</span><strong>{Number(v).toFixed(2)}</strong></div>)}<div><span>sum</span><strong>{Object.values(item.features).map(Number).reduce((sum: number, value: number)=>sum+value,0).toFixed(2)}</strong></div></div>{session&&auth.roles.includes('feed_admin')&&<button className="next" onClick={()=>void services.promoteBaseline(session.id,session.parameterVersion)}>Promote validated baseline</button>}</aside></div></section>
}
