import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Database, FlaskConical, LockKeyhole, Plus, ShieldCheck } from 'lucide-react';
import { services } from '../../lib/services';

export function TrainingPage() {
  const qc=useQueryClient(); const campaigns=useQuery({queryKey:['annotation-campaigns'],queryFn:services.listAnnotationCampaigns});
  const [selected,setSelected]=useState<string>(); const [tab,setTab]=useState('campaigns');
  const create=useMutation({mutationFn:()=>services.createAnnotationCampaign({code:`pilot-v1-${Date.now()}`,name:'Excerpt Quality Pilot V1',languagePolicy:{languages:['en','pt'],targetPerLanguage:50},samplingConfig:{seed:1337,strata:['language','dialogue','position','subject'],items:100}}),onSuccess:()=>qc.invalidateQueries({queryKey:['annotation-campaigns']})});
  const action=useMutation({mutationFn:({id,a}:{id:string;a:string})=>services.transitionAnnotationCampaign(id,a),onSuccess:()=>qc.invalidateQueries({queryKey:['annotation-campaigns']})});
  const sample=useMutation({mutationFn:services.sampleAnnotationCampaign});
  const dataset=useMutation({mutationFn:services.publishAnnotationDataset});
  const metrics=useQuery({queryKey:['annotation-metrics',selected],queryFn:()=>services.annotationMetrics(selected!),enabled:Boolean(selected)});
  const failure=[create,action,sample,dataset].find(m=>m.isError)?.error;
  return <section><header className="pagehead"><div><span className="eyebrow">TRAINING & GROUND TRUTH</span><h1>Excerpt quality</h1><p>Coleta humana cega para avaliar excerpts. Scores de modelo só aparecem depois do lock primário.</p></div><button className="button-action" onClick={()=>create.mutate()} disabled={create.isPending}><Plus size={16}/>Criar piloto 50 EN + 50 PT</button></header>{failure&&<div className="panel import-error"><strong>Ação não concluída</strong><p>{failure instanceof Error?failure.message:'O serviço recusou a operação. Consulte os logs do analytics.'}</p></div>}
    <div className="training-tabs">{[['campaigns','Campaigns'],['studio','Annotation Studio'],['review','Review & Adjudication'],['datasets','Datasets'],['evaluation','Model Evaluation']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
    {tab==='campaigns'&&<div className="panel"><div className="panelhead"><div><h2>Annotation campaigns</h2><span>Sampling versionado, três ratings por item e eventos auditáveis.</span></div><ShieldCheck size={20}/></div>{campaigns.isLoading&&<p>Carregando campanhas…</p>}{campaigns.data?.length===0&&!campaigns.isLoading&&<p>Nenhuma campanha criada. O piloto não é iniciado automaticamente.</p>}{campaigns.data?.map(c=><article className="campaign-card" key={c.id} onClick={()=>setSelected(c.id)}><div><strong>{c.name}</strong><small>{c.code} · {c.status} · {c.target_annotations_per_item} ratings/item</small><code>{c.id}</code></div><div className="runrow"><button onClick={e=>{e.stopPropagation();sample.mutate(c.id)}}>Sample 100</button><button onClick={e=>{e.stopPropagation();action.mutate({id:c.id,a:c.status==='DRAFT'?'start':'pause'})}}>{c.status==='DRAFT'?'Iniciar':'Pausar'}</button><button onClick={e=>{e.stopPropagation();dataset.mutate(c.id)}}>Publicar dataset</button></div></article>)}</div>}
    {tab==='studio'&&<BlindStudio/>}{tab==='review'&&<ReviewPanel campaignId={selected}/>} {tab==='datasets'&&<DatasetPanel campaignId={selected}/>} {tab==='evaluation'&&<div className="panel"><h2>Model Evaluation</h2><p>Comparações human × model serão exibidas com versão, idioma, MAE e Spearman. Correlação não implica validade de constructo.</p><FlaskConical size={28}/></div>}
    {selected&&<div className="panel"><h2>QA da campanha selecionada</h2>{metrics.isLoading?<p>Calculando…</p>:<pre>{JSON.stringify(metrics.data,null,2)}</pre>}</div>}</section>;
}
function BlindStudio(){const [campaign,setCampaign]=useState('');const [item,setItem]=useState<any>();const [hook,setHook]=useState(0);const [ratings,setRatings]=useState<Record<string,number>>({});const [locked,setLocked]=useState(false);const [context,setContext]=useState(false);const dims=['HOOK','CLARITY','AUTHENTICITY','IMPACT','PACING','SELF_CONTAINMENT'];const claim=async()=>{if(!campaign)return;setItem(await services.claimAnnotationItem(campaign));};const lock=async()=>{if(!item||Object.keys(ratings).length<6)return;await services.rateFirstScreen(item.campaignItemId,hook||3);await services.lockAnnotation(item.campaignItemId,ratings,3);setLocked(true);};return <div className="panel blind-studio"><h2>Annotation Studio</h2><div className="blind-banner"><LockKeyhole size={18}/> Modo cego ativo — nenhuma previsão de modelo é enviada antes do lock</div>{!item?<><p>Selecione uma campanha para reivindicar um item.</p><input aria-label="Campaign ID" value={campaign} onChange={e=>setCampaign(e.target.value)} placeholder="campaign UUID"/><button onClick={()=>void claim()}>Claim next item</button></>:<><p>Item <code>{item.campaignItemId}</code> — excerpt reservado sem scores de modelo.</p><blockquote>Texto disponível somente no fluxo autenticado de anotação.</blockquote><label>Primeira impressão (1–5)<select value={hook} onChange={e=>setHook(Number(e.target.value))}><option value={0}>Selecione</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>{dims.map(d=><label key={d}>{d}<select disabled={locked} value={ratings[d]??0} onChange={e=>setRatings({...ratings,[d]:Number(e.target.value)})}><option value={0}>Selecione</option>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}<button disabled={locked||Object.keys(ratings).length<6||!hook} onClick={()=>void lock()}>{locked?'Primary locked':'Lock primary annotation'}</button>{locked&&!context&&<button onClick={async()=>{await services.revealAnnotationContext(item.campaignItemId);setContext(true)}}>Reveal context</button>}{context&&<div className="context-box"><strong>Contexto liberado</strong><p>O contexto anterior e posterior pode ser consultado. Labels primários permanecem somente leitura.</p><button onClick={()=>void services.submitAnnotation(item.campaignItemId,true,3)}>Submit diagnostic</button></div>}</>}</div>}
function ReviewPanel({campaignId}:{campaignId?:string}){const q=useQuery({queryKey:['annotation-queue',campaignId],queryFn:()=>services.annotationQueue(campaignId!),enabled:Boolean(campaignId)});const [rationale,setRationale]=useState('');const [value,setValue]=useState(3);const adjudicate=useMutation({mutationFn:({item,dimension}:{item:string;dimension:string})=>services.adjudicateAnnotation(item,dimension,value,rationale),onSuccess:()=>q.refetch()});return <div className="panel"><h2>Review & Adjudication</h2><p>Discordâncias com amplitude igual ou maior que 2. Labels brutos permanecem preservados.</p>{!campaignId?<p>Selecione uma campanha na aba Campaigns.</p>:q.data?.items?.length===0?<p>Nenhum item na fila.</p>:q.data?.items?.map((item:any)=><article className="campaign-card" key={`${item.campaign_item_id}-${item.dimension_code}`}><div><strong>{item.dimension_code}</strong><small>item {item.campaign_item_id} · {item.min_value}–{item.max_value} ({item.ratings} ratings)</small></div><div><input aria-label="Rationale" placeholder="Rationale" value={rationale} onChange={e=>setRationale(e.target.value)}/><select value={value} onChange={e=>setValue(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><button onClick={()=>adjudicate.mutate({item:item.campaign_item_id,dimension:item.dimension_code})}>Adjudicate</button></div></article>)}</div>}
function DatasetPanel({campaignId}:{campaignId?:string}){const [version,setVersion]=useState(1);const [result,setResult]=useState<unknown>();return <div className="panel"><h2>Datasets imutáveis</h2><p>Snapshots guardam manifesto, labels brutos e adjudicações separadamente.</p>{!campaignId?<p>Selecione uma campanha na aba Campaigns.</p>:<><label>Version <input type="number" min={1} value={version} onChange={e=>setVersion(Number(e.target.value))}/></label><button onClick={async()=>setResult(await services.exportAnnotationDataset(campaignId,version))}>Export dataset</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</>}<Database size={28}/></div>}
