apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: publisher-service
  description: Publisher submissions and authorized metrics
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:default/book-platform
  system: book-catalog
