import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as AuthSession from 'expo-auth-session';
import * as WebBrowser from 'expo-web-browser';
import { StatusBar } from 'expo-status-bar';
import { Book, listBooks } from './src/api';

WebBrowser.maybeCompleteAuthSession();
const authority = process.env.EXPO_PUBLIC_OIDC_AUTHORITY ?? 'https://keycloak-bookrush.jteodoro.tec.br/realms/bookrush';
const clientId = process.env.EXPO_PUBLIC_OIDC_CLIENT_ID ?? 'bookrush-mobile';
const redirectUri = AuthSession.makeRedirectUri({ scheme: 'bookrush', path: 'callback' });
const discovery: AuthSession.DiscoveryDocument = { authorizationEndpoint: `${authority}/protocol/openid-connect/auth`, tokenEndpoint: `${authority}/protocol/openid-connect/token`, revocationEndpoint: `${authority}/protocol/openid-connect/revoke`, endSessionEndpoint: `${authority}/protocol/openid-connect/logout` };

export default function App() {
  const [request, response, promptAsync] = AuthSession.useAuthRequest({ clientId, redirectUri, responseType: AuthSession.ResponseType.Code, scopes: ['openid', 'profile', 'email'], usePKCE: true }, discovery);
  const [token, setToken] = useState<string>();
  const [books, setBooks] = useState<Book[]>([]);
  const [saved, setSaved] = useState<string[]>([]);
  const [query, setQuery] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [selected, setSelected] = useState<Book>();

  useEffect(() => { if (response?.type === 'success' && response.params.code) void exchangeCode(response.params.code); }, [response]);
  async function exchangeCode(code: string) { setBusy(true); setError(''); try { const result = await AuthSession.exchangeCodeAsync({ clientId, code, redirectUri, extraParams: { code_verifier: request?.codeVerifier ?? '' } }, discovery); setToken(result.accessToken); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível concluir o login.'); } finally { setBusy(false); } }
  async function loadBooks() { if (!token) return; setBusy(true); setError(''); try { setBooks((await listBooks(token, query)).items); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível carregar o catálogo.'); } finally { setBusy(false); } }
  const shown = useMemo(() => books, [books]);
  if (!token) return <SafeAreaView style={styles.center}><StatusBar style="dark" /><Text style={styles.logo}>B</Text><Text style={styles.kicker}>UM UNIVERSO DE HISTÓRIAS</Text><Text style={styles.title}>Seu próximo{`\n`}capítulo começa aqui.</Text><Text style={styles.subtitle}>Descubra livros que combinam com você.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={!request || busy} style={styles.primary} onPress={() => void promptAsync()}><Text style={styles.primaryText}>{busy ? 'Conectando…' : 'Entrar com Keycloak  →'}</Text></Pressable><Text style={styles.hint}>Login seguro · Tokens ficam apenas na memória</Text></SafeAreaView>;
  return <SafeAreaView style={styles.root}><StatusBar style="dark" /><View style={styles.header}><Text style={styles.brand}>BookRush</Text><Pressable onPress={() => setToken(undefined)}><Text style={styles.logout}>Sair</Text></Pressable></View><View style={styles.hero}><Text style={styles.kicker}>DESCUBRA SUA PRÓXIMA LEITURA</Text><Text style={styles.heading}>Histórias que <Text style={styles.italic}>ficam</Text>.</Text></View><View style={styles.search}><TextInput value={query} onChangeText={setQuery} placeholder="Buscar por título…" placeholderTextColor="#89978e" style={styles.input} onSubmitEditing={() => void loadBooks()} /><Pressable onPress={() => void loadBooks()}><Text style={styles.searchAction}>Buscar</Text></Pressable></View>{error ? <Text style={styles.error}>{error}</Text> : null}{busy ? <ActivityIndicator color="#d76c51" style={styles.loader} /> : null}<FlatList data={shown} keyExtractor={item => item.id} numColumns={2} columnWrapperStyle={styles.columns} contentContainerStyle={styles.list} renderItem={({ item, index }) => <BookCard book={item} index={index} saved={saved.includes(item.id)} onSave={() => setSaved(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])} onOpen={() => setSelected(item)} />} ListEmptyComponent={!busy ? <Text style={styles.empty}>Pesquise ou atualize para carregar o catálogo.</Text> : null} />{selected ? <View style={styles.modal}><Pressable style={styles.close} onPress={() => setSelected(undefined)}><Text style={styles.closeText}>×</Text></Pressable><Text style={styles.modalTitle}>{selected.canonicalTitle}</Text><Text style={styles.meta}>{selected.firstPublicationYear ?? 'Ano não informado'} · {selected.originalLanguage ?? 'Idioma não informado'}</Text><Text style={styles.modalBody}>{selected.description ?? 'Detalhes e trechos deste livro estarão disponíveis em breve.'}</Text><Pressable style={styles.primary} onPress={() => setSelected(undefined)}><Text style={styles.primaryText}>Continuar explorando</Text></Pressable></View> : null}</SafeAreaView>;
}
function BookCard({ book, index, saved, onSave, onOpen }: { book: Book; index: number; saved: boolean; onSave: () => void; onOpen: () => void }) { const colors = ['#c9654e', '#384e75', '#66816e', '#b28c48']; return <View style={styles.card}><Pressable onPress={onOpen} style={[styles.cover, { backgroundColor: colors[index % colors.length] }]}><Text style={styles.symbol}>✦</Text><Text style={styles.coverTitle}>{book.canonicalTitle}</Text><Text style={styles.coverLanguage}>{book.originalLanguage?.toUpperCase() ?? 'BOOKRUSH'}</Text></Pressable><View style={styles.cardFooter}><Text numberOfLines={2} style={styles.cardTitle}>{book.canonicalTitle}</Text><Pressable onPress={onSave}><Text style={styles.star}>{saved ? '★' : '☆'}</Text></Pressable></View></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: '#f7f7f2' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, backgroundColor: '#f7f7f2' }, logo: { backgroundColor: '#153d35', color: '#e9f0dd', borderRadius: 18, paddingHorizontal: 21, paddingVertical: 10, fontSize: 42, fontWeight: '700', marginBottom: 24 }, kicker: { color: '#7b8b83', fontSize: 11, letterSpacing: 1.5, fontWeight: '600' }, title: { color: '#20352e', fontSize: 38, lineHeight: 42, fontWeight: '700', textAlign: 'center', marginVertical: 14 }, subtitle: { color: '#718077', fontSize: 16, textAlign: 'center', marginBottom: 24 }, primary: { backgroundColor: '#153d35', borderRadius: 28, paddingHorizontal: 20, paddingVertical: 14, alignItems: 'center' }, primaryText: { color: '#fff', fontWeight: '700' }, hint: { color: '#94a098', fontSize: 11, marginTop: 14 }, error: { color: '#913f31', backgroundColor: '#fae8e2', padding: 10, borderRadius: 8, marginVertical: 10, textAlign: 'center' }, header: { height: 64, borderBottomWidth: 1, borderBottomColor: '#e4e8e1', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18 }, brand: { color: '#153d35', fontSize: 24, fontWeight: '700' }, logout: { color: '#356157' }, hero: { padding: 25 }, heading: { color: '#20352e', fontSize: 34, fontWeight: '700', marginTop: 10 }, italic: { color: '#d76c51', fontStyle: 'italic' }, search: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', marginHorizontal: 18, borderRadius: 12, paddingHorizontal: 12, borderWidth: 1, borderColor: '#dfe6df' }, input: { flex: 1, height: 46, color: '#20352e' }, searchAction: { color: '#244e42', fontWeight: '600' }, loader: { margin: 18 }, list: { padding: 18, paddingBottom: 30 }, columns: { gap: 14 }, card: { flex: 1, marginBottom: 22 }, cover: { aspectRatio: .72, borderRadius: 7, padding: 13, justifyContent: 'space-between' }, symbol: { alignSelf: 'flex-end', color: '#fff', fontSize: 30 }, coverTitle: { color: '#fff', fontSize: 18, fontWeight: '700' }, coverLanguage: { color: '#fff', fontSize: 10, letterSpacing: 1 }, cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: 8 }, cardTitle: { flex: 1, color: '#263a32', fontWeight: '700' }, star: { color: '#d76c51', fontSize: 25 }, empty: { color: '#718077', textAlign: 'center', marginTop: 60 }, modal: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#fbfbf7', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 26, shadowColor: '#17352e', shadowOpacity: .2, shadowRadius: 20 }, close: { position: 'absolute', right: 18, top: 10 }, closeText: { fontSize: 30, color: '#718078' }, modalTitle: { fontSize: 28, fontWeight: '700', color: '#263a32', marginTop: 18 }, meta: { color: '#7d8c83', marginVertical: 8 }, modalBody: { color: '#718078', lineHeight: 23, marginBottom: 18 } });
