apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookrush-mobile
  description: Aplicativo React Native/Expo para descoberta e estante BookRush.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: mobile-app
  lifecycle: experimental
  owner: group:default/book-platform
  system: book-catalog
  consumesApis:
    - catalog-api
