apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reader-bff-service
  description: Reader composition gateway
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:default/book-platform
  system: book-catalog
