package com.bookrush.publisherservice.api;
import java.security.Principal; import java.util.*; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import jakarta.validation.constraints.Size; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/v1/publisher") public class PublisherController { private final JdbcTemplate jdbc; private final com.bookrush.publisherservice.PublisherIngestionClient ingestion; public PublisherController(JdbcTemplate jdbc, com.bookrush.publisherservice.PublisherIngestionClient ingestion){this.jdbc=jdbc;this.ingestion=ingestion;} private String s(Principal p){if(p==null||p.getName()==null||p.getName().isBlank()) throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"authentication required"); return p.getName();} public record Submission(@NotBlank @Size(max=300) String title, UUID catalogBookId, String sourceCode, String sourceExternalId){}
 @PostMapping("/submissions") public Object create(@Valid @RequestBody Submission req,Principal p){UUID id=UUID.randomUUID();jdbc.update("insert into publisher.submission(id,subject_key,title,catalog_book_id,source_code,source_external_id) values(?,?,?,?,?,?)",id,s(p),req.title(),req.catalogBookId(),req.sourceCode(),req.sourceExternalId());return Map.of("id",id,"title",req.title(),"status","DRAFT");}
 @PostMapping("/submissions/{id}/submit") public Object submit(@PathVariable UUID id,Principal p){String subject=s(p);int n=jdbc.update("update publisher.submission set status='SUBMITTED',updated_at=now() where id=? and subject_key=? and status in ('DRAFT','UPLOADED')",id,subject);if(n==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"draft not found");var uploads=jdbc.queryForList("select object_key,content_type,sha256 from publisher.staged_upload where submission_id=? and subject_key=? and status='FINALIZED' order by finalized_at desc limit 1",id,subject);if(!uploads.isEmpty()){var upload=uploads.getFirst();ingestion.process(id, title(id,subject),String.valueOf(upload.get("object_key")),"books-staging",String.valueOf(upload.get("content_type")),String.valueOf(upload.get("sha256")));jdbc.update("update publisher.submission set status='PROCESSING',updated_at=now() where id=? and subject_key=?",id,subject);return Map.of("id",id,"status","PROCESSING");}return Map.of("id",id,"status","SUBMITTED");}
 private String title(UUID id,String subject){return jdbc.queryForObject("select title from publisher.submission where id=? and subject_key=?",String.class,id,subject);}
 @GetMapping("/submissions") public Object list(Principal p){return jdbc.queryForList("select id,title,status,catalog_book_id,source_code,source_external_id,ingestion_job_id,linked_at,created_at,updated_at from publisher.submission where subject_key=? order by created_at desc",s(p));}
 @GetMapping("/submissions/{id}") public Object get(@PathVariable UUID id,Principal p){var rows=jdbc.queryForList("select id,title,status,catalog_book_id,source_code,source_external_id,ingestion_job_id,linked_at,created_at,updated_at from publisher.submission where id=? and subject_key=?",id,s(p)); if(rows.isEmpty()) throw new ResponseStatusException(HttpStatus.NOT_FOUND,"submission not found"); return rows.getFirst();}
}
