package com.bookrush.analytics.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

/** Human ground-truth API. Raw labels are append-only; adjudication is separate. */
@RestController @RequestMapping("/api/admin/v1/annotation")
@Tag(name="Excerpt quality learning", description="Campanhas, anotação cega, adjudicação e datasets")
public class AnnotationLearningController {
  private final JdbcTemplate db; private final ObjectMapper json;
  private static final List<String> DIMENSIONS = List.of("HOOK","CLARITY","AUTHENTICITY","IMPACT","PACING","SELF_CONTAINMENT");
  public AnnotationLearningController(JdbcTemplate db,ObjectMapper json){this.db=db;this.json=json;}
  private String subject(Authentication a){return a==null||a.getName()==null?"unknown":a.getName();}
  private String hash(Object value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsBytes(value)));}catch(Exception e){throw new IllegalStateException(e);}}
  private Map<String,Object> body(Map<String,Object> b){return b==null?Map.of():b;}

  public record CampaignRequest(String code,String name,String protocolVersion,Integer targetAnnotationsPerItem,Map<String,Object> languagePolicy,Map<String,Object> samplingConfig){}
  @PostMapping("/campaigns") @Transactional @Operation(summary="Criar campanha")
  public ResponseEntity<?> create(@RequestBody CampaignRequest r, Authentication auth){
    if(r.code()==null||r.code().isBlank()||r.name()==null||r.name().isBlank()) return ResponseEntity.badRequest().body(Map.of("code","INVALID_CAMPAIGN"));
    var sampling=body(r.samplingConfig()); var hash=hash(sampling); var id=UUID.randomUUID();
    try{db.update("INSERT INTO analytics.annotation_campaign(id,code,name,protocol_version,target_annotations_per_item,language_policy,sampling_config,sampling_config_hash,created_by_subject) VALUES (?,?,?,?,?,?::jsonb,?::jsonb,?,?)",id,r.code(),r.name(),r.protocolVersion()==null?"annotation-protocol-v1":r.protocolVersion(),r.targetAnnotationsPerItem()==null?3:r.targetAnnotationsPerItem(),json.writeValueAsString(body(r.languagePolicy())),json.writeValueAsString(sampling),hash,subject(auth));}
    catch(Exception e){return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("code","CAMPAIGN_CODE_EXISTS"));}
    return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("id",id,"code",r.code(),"status","DRAFT","samplingConfigHash",hash));
  }
  @PostMapping("/campaigns/{id}/sample") @Transactional @Operation(summary="Materializar amostra estratificada")
  public ResponseEntity<?> sample(@PathVariable UUID id,@RequestBody(required=false) Map<String,Object> config){
    var campaign=db.queryForList("SELECT target_annotations_per_item FROM analytics.annotation_campaign WHERE id=?",id); if(campaign.isEmpty())return ResponseEntity.notFound().build(); int limit=config!=null&&config.get("items") instanceof Number n?Math.min(1000,Math.max(1,n.intValue())):100;
    int inserted=db.update("INSERT INTO analytics.annotation_campaign_item(id,campaign_id,excerpt_id,sampling_stratum,sampling_reason,priority,target_annotations) SELECT gen_random_uuid(),?,e.id,COALESCE(b.original_language,'und')||':position', 'seeded deterministic sample', (row_number() over())::int, c.target_annotations_per_item FROM analytics.excerpt e JOIN catalog.book_asset_version v ON v.id=e.source_asset_version_id JOIN catalog.book_asset a ON a.id=v.book_asset_id JOIN catalog.book b ON b.id=a.book_id CROSS JOIN analytics.annotation_campaign c WHERE c.id=? AND NOT EXISTS (SELECT 1 FROM analytics.annotation_campaign_item x WHERE x.campaign_id=c.id AND x.excerpt_id=e.id) ORDER BY md5(e.id::text||?) LIMIT ?",id,id,String.valueOf(config==null?1337:config.getOrDefault("seed",1337)),limit);
    return ResponseEntity.ok(Map.of("campaignId",id,"inserted",inserted,"requested",limit,"samplingConfigHash",hash(config==null?Map.of():config)));
  }
  @GetMapping("/campaigns") @Operation(summary="Listar campanhas")
  public Map<String,Object> campaigns(){var rows=db.queryForList("SELECT id,code,name,status,protocol_version,target_annotations_per_item,created_by_subject,created_at,updated_at FROM analytics.annotation_campaign ORDER BY created_at DESC"); return Map.of("items",rows,"total",rows.size());}
  @PostMapping("/campaigns/{id}/{action}") @Transactional @Operation(summary="Alterar ciclo de vida")
  public ResponseEntity<?> transition(@PathVariable UUID id,@PathVariable String action,Authentication auth){
    String next=switch(action){case "start"->"RUNNING";case "pause"->"PAUSED";case "complete"->"COMPLETED";case "cancel"->"CANCELLED";default->null;}; if(next==null)return ResponseEntity.badRequest().body(Map.of("code","INVALID_ACTION"));
    int n=db.update("UPDATE analytics.annotation_campaign SET status=?,updated_at=now(),version=version+1 WHERE id=? AND ((status='DRAFT' AND ?='RUNNING') OR (status='RUNNING' AND ? IN ('PAUSED','COMPLETED','CANCELLED')) OR (status='PAUSED' AND ? IN ('RUNNING','CANCELLED'))) ",next,id,next,next,next);
    if(n==0)return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("code","INVALID_TRANSITION")); event(null,null,"CAMPAIGN_"+action.toUpperCase(),auth,Map.of()); return ResponseEntity.ok(Map.of("id",id,"status",next));
  }
  @PostMapping("/campaigns/{id}/claim-next") @Transactional @Operation(summary="Reivindicar próximo item")
  public ResponseEntity<?> claim(@PathVariable UUID id,@RequestParam(defaultValue="900") long ttl,Authentication auth){
    String who=subject(auth); var items=db.queryForList("SELECT i.id,i.excerpt_id FROM analytics.annotation_campaign_item i WHERE i.campaign_id=? AND i.state IN ('PENDING','IN_PROGRESS') AND NOT EXISTS (SELECT 1 FROM analytics.annotation_assignment a WHERE a.campaign_item_id=i.id AND a.status='ACTIVE' AND a.expires_at>now() AND a.annotator_subject<>?) ORDER BY i.priority DESC,i.created_at LIMIT 1",id,who);
    if(items.isEmpty())return ResponseEntity.noContent().build(); var item=items.getFirst(); UUID itemId=(UUID)item.get("id"); UUID assignment=UUID.randomUUID(); db.update("INSERT INTO analytics.annotation_assignment(id,campaign_item_id,annotator_subject,expires_at) VALUES (?,?,?,now()+(?||' seconds')::interval) ON CONFLICT(campaign_item_id,annotator_subject) DO UPDATE SET expires_at=excluded.expires_at,status='ACTIVE',version=annotation_assignment.version+1",assignment,itemId,who,Math.max(60,Math.min(ttl,86400))); db.update("UPDATE analytics.annotation_campaign_item SET state='IN_PROGRESS' WHERE id=?",itemId); return ResponseEntity.ok(Map.of("assignmentId",assignment,"campaignItemId",itemId,"excerptId",item.get("excerpt_id"),"expiresInSeconds",ttl));
  }
  @GetMapping("/items/{itemId}") @Operation(summary="Obter item em modo cego")
  public ResponseEntity<?> item(@PathVariable UUID itemId,Authentication auth){String who=subject(auth); var rows=db.queryForList("SELECT i.id,i.campaign_id,i.excerpt_id,i.sampling_stratum,i.state,a.id annotation_id,a.status annotation_status,a.primary_locked_at FROM analytics.annotation_campaign_item i LEFT JOIN analytics.annotation a ON a.campaign_item_id=i.id AND a.annotator_subject=? WHERE i.id=?",who,itemId); if(rows.isEmpty())return ResponseEntity.notFound().build(); var row=new LinkedHashMap<>(rows.getFirst()); row.put("blind",true); row.remove("excerpt_text"); return ResponseEntity.ok(row);}
  public record FirstScreen(Integer hook){ }
  @PostMapping("/items/{itemId}/first-screen") @Transactional @Operation(summary="Registrar primeira impressão")
  public ResponseEntity<?> first(@PathVariable UUID itemId,@RequestBody FirstScreen r,Authentication auth){if(r.hook()==null||r.hook()<1||r.hook()>5)return ResponseEntity.badRequest().body(Map.of("code","INVALID_ORDINAL")); UUID aid=ensureAnnotation(itemId,subject(auth)); db.update("UPDATE analytics.annotation SET first_screen_hook=?,updated_at=now(),version=version+1 WHERE id=? AND primary_locked_at IS NULL",r.hook(),aid); event(aid,itemId,"FIRST_SCREEN_RATED",auth,Map.of("hook",r.hook())); return ResponseEntity.ok(Map.of("annotationId",aid,"recorded",true));}
  public record FullRating(Map<String,Integer> dimensions,Set<String> failureTags,Integer confidence){ }
  @PostMapping("/items/{itemId}/lock") @Transactional @Operation(summary="Bloquear anotação primária sem revelar contexto")
  public ResponseEntity<?> lock(@PathVariable UUID itemId,@RequestBody FullRating r,Authentication auth){String who=subject(auth); UUID aid=ensureAnnotation(itemId,who); if(r.dimensions()==null||!r.dimensions().keySet().containsAll(DIMENSIONS))return ResponseEntity.badRequest().body(Map.of("code","INCOMPLETE_DIMENSIONS","required",DIMENSIONS)); for(var e:r.dimensions().entrySet()){if(e.getValue()==null||e.getValue()<1||e.getValue()>5)return ResponseEntity.badRequest().body(Map.of("code","INVALID_ORDINAL","dimension",e.getKey())); db.update("INSERT INTO analytics.annotation_dimension_value(annotation_id,dimension_code,stage,ordinal_value) VALUES (?,?,'FULL_EXCERPT',?) ON CONFLICT DO UPDATE SET ordinal_value=excluded.ordinal_value",aid,e.getKey(),e.getValue());} if(r.failureTags()!=null)for(String tag:r.failureTags())db.update("INSERT INTO analytics.annotation_failure_tag(annotation_id,tag) VALUES (?,?) ON CONFLICT DO NOTHING",aid,tag); db.update("UPDATE analytics.annotation SET confidence=?,status='LOCKED',primary_locked_at=now(),version=version+1 WHERE id=? AND primary_locked_at IS NULL",r.confidence(),aid); event(aid,itemId,"LOCKED",auth,Map.of()); return ResponseEntity.ok(Map.of("annotationId",aid,"locked",true,"contextAvailable",true));}
  @GetMapping("/items/{itemId}/context") @Operation(summary="Revelar contexto após lock")
  public ResponseEntity<?> context(@PathVariable UUID itemId,Authentication auth){String who=subject(auth); var locked=db.queryForList("SELECT a.id FROM analytics.annotation a WHERE a.campaign_item_id=? AND a.annotator_subject=? AND a.primary_locked_at IS NOT NULL",itemId,who); if(locked.isEmpty())return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("code","CONTEXT_LOCK_REQUIRED")); db.update("UPDATE analytics.annotation SET context_revealed_at=COALESCE(context_revealed_at,now()) WHERE id=?",locked.getFirst().get("id")); var rows=db.queryForList("SELECT e.id,e.text,e.start_codepoint,e.end_codepoint FROM analytics.annotation_campaign_item i JOIN analytics.excerpt e ON e.id=i.excerpt_id WHERE i.id=?",itemId); return ResponseEntity.ok(Map.of("itemId",itemId,"context",rows,"primaryReadOnly",true));}
  public record Diagnostic(Boolean contextRequired,Integer severity,String notes){ }
  @PostMapping("/items/{itemId}/submit") @Transactional @Operation(summary="Submeter diagnóstico pós-lock")
  public ResponseEntity<?> submit(@PathVariable UUID itemId,@RequestBody Diagnostic d,Authentication auth){String who=subject(auth); var a=db.queryForList("SELECT id FROM analytics.annotation WHERE campaign_item_id=? AND annotator_subject=? AND primary_locked_at IS NOT NULL",itemId,who); if(a.isEmpty())return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("code","PRIMARY_LOCK_REQUIRED")); UUID aid=(UUID)a.getFirst().get("id"); db.update("INSERT INTO analytics.annotation_context_diagnostic(annotation_id,context_required,severity,notes) VALUES (?,?,?,?) ON CONFLICT(annotation_id) DO UPDATE SET context_required=excluded.context_required,severity=excluded.severity,notes=excluded.notes",aid,d.contextRequired(),d.severity(),d.notes()); db.update("UPDATE analytics.annotation SET status='SUBMITTED',submitted_at=COALESCE(submitted_at,now()),version=version+1 WHERE id=?",aid); db.update("UPDATE analytics.annotation_assignment SET status='COMPLETED' WHERE campaign_item_id=? AND annotator_subject=?",itemId,who); db.update("UPDATE analytics.annotation_campaign_item SET state='COMPLETE' WHERE id=? AND (SELECT count(*) FROM analytics.annotation WHERE campaign_item_id=? AND status='SUBMITTED')>=target_annotations",itemId,itemId); event(aid,itemId,"SUBMITTED",auth,Map.of()); return ResponseEntity.ok(Map.of("annotationId",aid,"status","SUBMITTED"));}
  @GetMapping("/campaigns/{id}/metrics") @Operation(summary="Métricas operacionais e QA")
  public Map<String,Object> metrics(@PathVariable UUID id){var dist=db.queryForList("SELECT dv.dimension_code,avg(dv.ordinal_value) mean,percentile_cont(.5) within group(order by dv.ordinal_value) median,percentile_cont(.75) within group(order by dv.ordinal_value)-percentile_cont(.25) within group(order by dv.ordinal_value) iqr,count(*) count FROM analytics.annotation_dimension_value dv JOIN analytics.annotation a ON a.id=dv.annotation_id JOIN analytics.annotation_campaign_item i ON i.id=a.campaign_item_id WHERE i.campaign_id=? GROUP BY dv.dimension_code ORDER BY dv.dimension_code",id); var counts=db.queryForMap("SELECT count(*) total,count(*) FILTER(WHERE status='SUBMITTED') submitted,count(DISTINCT annotator_subject) annotators,avg(extract(epoch from (submitted_at-created_at))*1000) elapsed_ms FROM analytics.annotation a JOIN analytics.annotation_campaign_item i ON i.id=a.campaign_item_id WHERE i.campaign_id=?",id); return Map.of("campaignId",id,"dimensions",dist,"counts",counts,"qaStatus",dist.isEmpty()?"INSUFFICIENT_SAMPLE":"AVAILABLE");}
  @GetMapping("/campaigns/{id}/adjudication-queue") @Operation(summary="Listar discordâncias")
  public Map<String,Object> disagreement(@PathVariable UUID id){var rows=db.queryForList("SELECT i.id campaign_item_id,d.dimension_code,min(d.ordinal_value) min_value,max(d.ordinal_value) max_value,count(*) ratings FROM analytics.annotation_campaign_item i JOIN analytics.annotation a ON a.campaign_item_id=i.id JOIN analytics.annotation_dimension_value d ON d.annotation_id=a.id WHERE i.campaign_id=? GROUP BY i.id,d.dimension_code HAVING max(d.ordinal_value)-min(d.ordinal_value)>=2 ORDER BY i.id,d.dimension_code",id); return Map.of("campaignId",id,"items",rows,"threshold",2,"total",rows.size());}
  public record Adjudication(String dimensionCode,Integer ordinalValue,String rationale){}
  @PostMapping("/items/{itemId}/adjudicate") @Transactional @Operation(summary="Registrar adjudicação sem alterar labels brutos")
  public ResponseEntity<?> adjudicate(@PathVariable UUID itemId,@RequestBody Adjudication a,Authentication auth){if(a.rationale()==null||a.rationale().isBlank())return ResponseEntity.badRequest().body(Map.of("code","RATIONALE_REQUIRED")); if(a.ordinalValue()!=null&&(a.ordinalValue()<1||a.ordinalValue()>5))return ResponseEntity.badRequest().body(Map.of("code","INVALID_ORDINAL")); UUID id=UUID.randomUUID(); db.update("INSERT INTO analytics.annotation_adjudication(id,campaign_item_id,reviewer_subject,dimension_code,ordinal_value,rationale) VALUES (?,?,?,?,?,?)",id,itemId,subject(auth),a.dimensionCode(),a.ordinalValue(),a.rationale()); event(null,itemId,"ADJUDICATED",auth,Map.of("dimension",String.valueOf(a.dimensionCode()))); return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("id",id,"rawLabelsPreserved",true));}
  @PostMapping("/campaigns/{id}/datasets") @Transactional @Operation(summary="Publicar snapshot imutável")
  public ResponseEntity<?> dataset(@PathVariable UUID id,Authentication auth){Integer version=db.queryForObject("SELECT COALESCE(max(version_number),0)+1 FROM analytics.annotation_dataset_version WHERE campaign_id=?",Integer.class,id); String manifest=hash(List.of(id,version,Instant.now().toString())); UUID did=UUID.randomUUID(); db.update("INSERT INTO analytics.annotation_dataset_version(id,campaign_id,version_number,manifest_sha256,created_by_subject) VALUES (?,?,?,?,?)",did,id,version,manifest,subject(auth)); db.update("INSERT INTO analytics.annotation_dataset_item(dataset_version_id,campaign_item_id,raw_labels,adjudicated_labels) SELECT ?,i.id,COALESCE(jsonb_agg(jsonb_build_object('annotationId',a.id,'annotator',a.annotator_subject,'dimensions',(SELECT jsonb_object_agg(dimension_code,ordinal_value) FROM analytics.annotation_dimension_value WHERE annotation_id=a.id))), '[]'::jsonb),COALESCE((SELECT jsonb_agg(jsonb_build_object('reviewer',ad.reviewer_subject,'dimension',ad.dimension_code,'value',ad.ordinal_value,'rationale',ad.rationale)) FROM analytics.annotation_adjudication ad WHERE ad.campaign_item_id=i.id),'[]'::jsonb) FROM analytics.annotation_campaign_item i LEFT JOIN analytics.annotation a ON a.campaign_item_id=i.id WHERE i.campaign_id=? GROUP BY i.id",did,id); return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("id",did,"version",version,"manifestSha256",manifest,"immutable",true));}
  @GetMapping("/campaigns/{id}/datasets/{version}/export") @Operation(summary="Exportar dataset publicado")
  public ResponseEntity<?> export(@PathVariable UUID id,@PathVariable int version){var rows=db.queryForList("SELECT d.id,d.version_number,d.manifest_sha256,i.campaign_item_id,i.raw_labels,i.adjudicated_labels FROM analytics.annotation_dataset_version d JOIN analytics.annotation_dataset_item i ON i.dataset_version_id=d.id WHERE d.campaign_id=? AND d.version_number=? AND d.status='PUBLISHED'",id,version); return rows.isEmpty()?ResponseEntity.notFound().build():ResponseEntity.ok(Map.of("campaignId",id,"version",version,"items",rows));}
  private UUID ensureAnnotation(UUID item,String who){var rows=db.queryForList("SELECT id FROM analytics.annotation WHERE campaign_item_id=? AND annotator_subject=?",item,who); if(!rows.isEmpty())return (UUID)rows.getFirst().get("id"); UUID id=UUID.randomUUID(); db.update("INSERT INTO analytics.annotation(id,campaign_item_id,annotator_subject,protocol_version) SELECT ?,id,?,'annotation-protocol-v1' FROM analytics.annotation_campaign_item WHERE id=?",id,who,item); return id;}
  private void event(UUID aid,UUID item,String type,Authentication auth,Map<String,Object> payload){try{db.update("INSERT INTO analytics.annotation_event(id,annotation_id,campaign_item_id,event_type,actor_subject,payload) VALUES (?,?,?,?,?,?::jsonb)",UUID.randomUUID(),aid,item,type,subject(auth),json.writeValueAsString(payload));}catch(Exception ignored){}}
}
